# ==============================================================================
# Basic System Configuration
# ==============================================================================
# Enable C++ language support
CONFIG_CPP=y
# Enable the standard C++ library (Glibcxx/Libc++)
CONFIG_GLIBCXX_LIBCPP=y
# Use Newlib C Library
CONFIG_NEWLIB_LIBC=y
# Enable floating-point formatting support (%f) for printf functions in Newlib
CONFIG_NEWLIB_LIBC_FLOAT_PRINTF=y

# Enable the FPU (Floating Point Unit)
CONFIG_FPU=y

# Increase the main thread stack size to 8192 bytes (often needed for ML models)
CONFIG_MAIN_STACK_SIZE=8192


# ==============================================================================
# Logging & Console
# ==============================================================================
# Enable the logging system
CONFIG_LOG=y
# Set the stack size for the log processing thread to 1024 bytes
CONFIG_LOG_PROCESS_THREAD_STACK_SIZE=1024

# Enable assert functionality for debugging
CONFIG_ASSERT=y

# Enable the console subsystem
CONFIG_CONSOLE=y
# Enable the UART console backend
CONFIG_UART_CONSOLE=y
# Enable line-editing support for the console
CONFIG_CONSOLE_GETLINE=y


# ==============================================================================
# Hardware Drivers
# ==============================================================================
# Enable GPIO (General-Purpose Input/Output) driver
CONFIG_GPIO=y
# Enable I2C (Inter-Integrated Circuit) driver
CONFIG_I2C=y
# Enable the sensor subsystem
CONFIG_SENSOR=y

CONFIG_MPU6050=y

# ==============================================================================
# Thread Analyzer & Runtime Statistics
# ==============================================================================
CONFIG_THREAD_ANALYZER=y
CONFIG_THREAD_ANALYZER_USE_PRINTK=y
CONFIG_THREAD_ANALYZER_AUTO=y
CONFIG_THREAD_ANALYZER_AUTO_INTERVAL=5
CONFIG_THREAD_NAME=y
CONFIG_SCHED_THREAD_USAGE=y
CONFIG_SCHED_THREAD_USAGE_ALL=y

# ==============================================================================
# Display & GUI (LVGL)
# ==============================================================================
CONFIG_DISPLAY=y
CONFIG_LVGL=y
CONFIG_INPUT=y
CONFIG_SHELL=y
CONFIG_LV_USE_LOG=y
CONFIG_LV_Z_MEM_POOL_SIZE=16384
CONFIG_LV_USE_LABEL=y
CONFIG_LV_USE_ARC=y
CONFIG_LV_USE_MONKEY=y
CONFIG_LV_FONT_MONTSERRAT_14=y
CONFIG_LV_FONT_MONTSERRAT_20=y
CONFIG_LV_FONT_MONTSERRAT_32=y
CONFIG_LV_FONT_MONTSERRAT_48=y
